// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  created_at: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = Entity<{
  firstname: string;
  lastname: string;
  email: string;
  role: 'ADMIN' | 'SPONSOR' | 'VOLUNTEER' | 'REQUESTER';
  bio: string;
}>;

export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

/**
 * Project-related types that match the backend models
 */
export type Project = Entity<{
  id: string;
  title: string;
  description: string;
  project_type: string;
  preferred_technologies: string | null;
  estimated_timeline:
    | 'LESS_THAN_1_MONTH'
    | 'ONE_TO_THREE_MONTHS'
    | 'THREE_TO_SIX_MONTHS'
    | 'MORE_THAN_SIX_MONTHS'
    | null;
  created_at: string;
  updated_at: string;
  requester_id: string;
  status: string;
}>;
