"""Change User Model

Revision ID: 0ac1f7ae3b05
Revises: 1a31ce608336
Create Date: 2025-06-30 15:07:04.668877

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ac1f7ae3b05'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', 'USER', name='userrole').create(op.get_bind())
    op.add_column('user', sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='userrole', create_type=False), nullable=True))
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user', 'role')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    sa.Enum('ADMIN', 'USER', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
