"""add volunteer roles table

Revision ID: 0fd3b7bf2dd3
Revises: 621ef7cc6186
Create Date: 2025-10-17 18:07:08.002107

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fd3b7bf2dd3'
down_revision = '621ef7cc6186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('FRONTEND', 'BACKEND', 'FULLSTACK', 'UIUX', 'PROJECTMANAGER', 'QA', name='volunteerrole').create(op.get_bind())
    op.create_table('uservolunteerrole',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', postgresql.ENUM('FRONTEND', 'BACKEND', 'FULLSTACK', 'UIUX', 'PROJECTMANAGER', 'QA', name='volunteerrole', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uservolunteerrole')
    sa.Enum('FRONTEND', 'BACKEND', 'FULLSTACK', 'UIUX', 'PROJECTMANAGER', 'QA', name='volunteerrole').drop(op.get_bind())
    # ### end Alembic commands ###
