"""Create withdrawal table

Revision ID: 13e72d48e280
Revises: 0bfa3c4b3def
Create Date: 2025-10-20 11:43:42.049559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13e72d48e280'
down_revision = '0bfa3c4b3def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NOT_WITHDRAWN', 'PENDING', 'COMPLETED',
            name='withdrawalstatus').create(op.get_bind())
    op.create_table('withdrawal',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('recipient_id', sa.Uuid(), nullable=False),
                    sa.Column('amount_requested', sa.Float(), nullable=False),
                    sa.Column('fee_percentage', sa.Float(), nullable=False),
                    sa.Column('fee_amount', sa.Float(), nullable=False),
                    sa.Column('amount_to_transfer',
                              sa.Float(), nullable=False),
                    sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('account_holder_name', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('status', postgresql.ENUM('NOT_WITHDRAWN', 'PENDING', 'COMPLETED',
                                                        name='withdrawalstatus', create_type=False), nullable=True),
                    sa.Column('requested_at', sa.DateTime(), nullable=False),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['recipient_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdrawal')
    sa.Enum('NOT_WITHDRAWN', 'PENDING', 'COMPLETED',
            name='withdrawalstatus').drop(op.get_bind())
    # ### end Alembic commands ###
