"""sponsor_profile table create

Revision ID: 143ab2510fe8
Revises: e7b91cb2ffd3
Create Date: 2025-10-20 18:24:10.462815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '143ab2510fe8'
down_revision = 'e7b91cb2ffd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsorprofile',
    sa.Column('tagline', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('about', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('twitter_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('facebook_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('instagram_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsorprofile')
    # ### end Alembic commands ###
