"""change_estimated_timeline_to_enum

Revision ID: 1ade11869bda
Revises: a2dd44980f21
Create Date: 2025-07-12 19:28:04.287961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1ade11869bda'
down_revision = 'a2dd44980f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('LESS_THAN_1_MONTH', 'ONE_TO_THREE_MONTHS', 'THREE_TO_SIX_MONTHS', 'MORE_THAN_SIX_MONTHS', name='estimatedtimeline').create(op.get_bind())
    op.alter_column('project', 'estimated_timeline',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('LESS_THAN_1_MONTH', 'ONE_TO_THREE_MONTHS', 'THREE_TO_SIX_MONTHS', 'MORE_THAN_SIX_MONTHS', name='estimatedtimeline'),
               existing_nullable=True,
               postgresql_using='estimated_timeline::estimatedtimeline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'estimated_timeline',
               existing_type=sa.Enum('LESS_THAN_1_MONTH', 'ONE_TO_THREE_MONTHS', 'THREE_TO_SIX_MONTHS', 'MORE_THAN_SIX_MONTHS', name='estimatedtimeline'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    sa.Enum('LESS_THAN_1_MONTH', 'ONE_TO_THREE_MONTHS', 'THREE_TO_SIX_MONTHS', 'MORE_THAN_SIX_MONTHS', name='estimatedtimeline').drop(op.get_bind())
    # ### end Alembic commands ###
