"""Add parent-child relationship to comments for replies

Revision ID: 3290de641612
Revises: cb1454e110b3
Create Date: 2025-08-17 23:49:13.855564

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3290de641612'
down_revision = 'cb1454e110b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
