"""Add sponsorship table

Revision ID: 44bbce558570
Revises: ba5572617b64
Create Date: 2025-10-19 18:01:30.363835

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44bbce558570'
down_revision = 'ba5572617b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsorship',
                    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(
                        length=500), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('sponsor_id', sa.Uuid(), nullable=False),
                    sa.Column('recipient_id', sa.Uuid(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['payment.order_id'], ),
                    sa.ForeignKeyConstraint(
                        ['recipient_id'], ['user.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['sponsor_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('order_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsorship')
    # ### end Alembic commands ###
