"""Add project applications table

Revision ID: 46cc271bb00c
Revises: 26788788c5d2
Create Date: 2025-08-12 19:19:44.248898

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46cc271bb00c'
down_revision = '26788788c5d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='applicationstatus').create(op.get_bind())
    sa.Enum('FIVE_TO_TEN', 'TEN_TO_TWENTY', 'TWENTY_TO_THIRTY', 'THIRTY_PLUS', name='availability').create(op.get_bind())
    sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='experiencelevel').create(op.get_bind())
    sa.Enum('FRONTEND', 'BACKEND', 'FULLSTACK', 'UIUX', 'MOBILE', 'DEVOPS', 'QA', 'PM', name='developerrole').create(op.get_bind())
    op.create_table('projectapplication',
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('linkedin', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('github', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('portfolio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('role', postgresql.ENUM('FRONTEND', 'BACKEND', 'FULLSTACK', 'UIUX', 'MOBILE', 'DEVOPS', 'QA', 'PM', name='developerrole', create_type=False), nullable=True),
    sa.Column('experience_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='experiencelevel', create_type=False), nullable=True),
    sa.Column('motivation', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('relevant_experience', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('availability', postgresql.ENUM('FIVE_TO_TEN', 'TEN_TO_TWENTY', 'TWENTY_TO_THIRTY', 'THIRTY_PLUS', name='availability', create_type=False), nullable=True),
    sa.Column('preferred_technologies', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='applicationstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projectapplication')
    sa.Enum('FRONTEND', 'BACKEND', 'FULLSTACK', 'UIUX', 'MOBILE', 'DEVOPS', 'QA', 'PM', name='developerrole').drop(op.get_bind())
    sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='experiencelevel').drop(op.get_bind())
    sa.Enum('FIVE_TO_TEN', 'TEN_TO_TWENTY', 'TWENTY_TO_THIRTY', 'THIRTY_PLUS', name='availability').drop(op.get_bind())
    sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='applicationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
