"""Add project thread and comment models

Revision ID: 473aea1573c4
Revises: 594f91509ddb
Create Date: 2025-07-18 02:37:18.149353

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '473aea1573c4'
down_revision = '594f91509ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
