"""Add Apllication Review Permission Table

Revision ID: 6ece03d315cc
Revises: 0fd3b7bf2dd3
Create Date: 2025-10-18 16:15:11.661183

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ece03d315cc'
down_revision = '0fd3b7bf2dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'REVOKED', name='reviewerpermissionstatus').create(op.get_bind())
    op.create_table('applicationreviewerpermission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'REVOKED', name='reviewerpermissionstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicationreviewerpermission')
    sa.Enum('ACTIVE', 'REVOKED', name='reviewerpermissionstatus').drop(op.get_bind())
    # ### end Alembic commands ###
