"""add_developer_roles_to_user_table

Revision ID: 8728cb2e4112
Revises: 48477a7a5efb
Create Date: 2025-08-18 19:55:05.757086

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8728cb2e4112'
down_revision = '48477a7a5efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('developer_roles', sa.JSON(), nullable=True))
    op.drop_column('user', 'development_roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('development_roles', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('user', 'developer_roles')
    # ### end Alembic commands ###
