"""Add project table

Revision ID: a2dd44980f21
Revises: dba78649afa2
Create Date: 2025-07-07 16:43:07.598419

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2dd44980f21'
down_revision = 'dba78649afa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', name='projectstatus').create(op.get_bind())
    sa.Enum('WEBSITE', 'MOBILE_APP', 'DATABASE', 'API', 'DESKTOP_APP', 'OTHER', name='projecttype').create(op.get_bind())
    op.create_table('project',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('project_type', postgresql.ENUM('WEBSITE', 'MOBILE_APP', 'DATABASE', 'API', 'DESKTOP_APP', 'OTHER', name='projecttype', create_type=False), nullable=True),
    sa.Column('preferred_technologies', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('estimated_timeline', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', name='projectstatus', create_type=False), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    sa.Enum('WEBSITE', 'MOBILE_APP', 'DATABASE', 'API', 'DESKTOP_APP', 'OTHER', name='projecttype').drop(op.get_bind())
    sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', name='projectstatus').drop(op.get_bind())
    # ### end Alembic commands ###
