"""Add assignee_id to Task model

Revision ID: a3fd6d6639be
Revises: 1964310c3093
Create Date: 2025-08-17 19:55:09.751589

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a3fd6d6639be'
down_revision = '1964310c3093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('assignee_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'assignee_id')
    # ### end Alembic commands ###
