"""Add donations table

Revision ID: b8a6b6cf89e8
Revises: b8305aaaaa06
Create Date: 2025-10-16 05:53:45.120598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b8a6b6cf89e8'
down_revision = 'b8305aaaaa06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment', ['order_id'])

    op.create_table('donation',
                    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(
                        length=500), nullable=True),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('donor_id', sa.Uuid(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['donor_id'], ['user.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['payment.order_id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('order_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_table('donation')
    # ### end Alembic commands ###
