"""Add order not found payment status

Revision ID: ba5572617b64
Revises: 404c7d59dcf3
Create Date: 2025-10-19 07:40:59.885636

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'ba5572617b64'
down_revision = '404c7d59dcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentstatus',
        new_values=['PENDING', 'CANCELLED', 'FAILED', 'CHARGEDBACK', 'NOT_FOUND', 'SUCCESS'],
        affected_columns=[TableReference(table_schema='public', table_name='payment', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='paymentstatus',
        new_values=['PENDING', 'CANCELLED', 'FAILED', 'CHARGEDBACK', 'SUCCESS'],
        affected_columns=[TableReference(table_schema='public', table_name='payment', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
