"""add creator_id to task

Revision ID: bbd75779f2c8
Revises: 0fd3b7bf2dd3
Create Date: 2025-10-18 15:17:39.464813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bbd75779f2c8'
down_revision = '0fd3b7bf2dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('creator_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'creator_id')
    # ### end Alembic commands ###
