"""Add task table and enums

Revision ID: bc9333809f95
Revises: 1ade11869bda
Create Date: 2025-07-17 17:12:36.711195

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc9333809f95'
down_revision = '1ade11869bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority').create(op.get_bind())
    sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus').create(op.get_bind())
    op.create_table('task',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('status', postgresql.ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus', create_type=False), nullable=True),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority', create_type=False), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus').drop(op.get_bind())
    sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority').drop(op.get_bind())
    # ### end Alembic commands ###
