"""Add User Roles

Revision ID: dba78649afa2
Revises: 0ac1f7ae3b05
Create Date: 2025-07-02 10:11:12.519772

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'dba78649afa2'
down_revision = '0ac1f7ae3b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='userrole',
        new_values=['ADMIN', 'VOLUNTEER', 'REQUESTER', 'SPONSOR'],
        affected_columns=[TableReference(table_schema='public', table_name='user', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='userrole',
        new_values=['ADMIN', 'USER'],
        affected_columns=[TableReference(table_schema='public', table_name='user', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
