"""Add opening positions table and models

Revision ID: e7b91cb2ffd3
Revises: 13e72d48e280
Create Date: 2025-10-20 16:48:26.985944

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7b91cb2ffd3'
down_revision = '13e72d48e280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openposition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('volunteer_role', postgresql.ENUM('FRONTEND', 'BACKEND', 'FULLSTACK', 'UIUX', 'MOBILE', 'DEVOPS', 'QA', 'PM', name='developerrole', create_type=False), nullable=True),
    sa.Column('openings_count', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openposition')
    # ### end Alembic commands ###
