"""add notification settings to user table

Revision ID: f0e862c435c7
Revises: f3e2d1c9a8b7
Create Date: 2025-08-18 17:36:59.683385

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f0e862c435c7'
down_revision = 'f3e2d1c9a8b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user', sa.Column('sms_notifications', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('push_notifications', sa.Boolean(), nullable=False, server_default='true'))
    op.drop_constraint(op.f('volunteerexperience_profile_id_fkey'), 'volunteerexperience', type_='foreignkey')
    op.create_foreign_key(None, 'volunteerexperience', 'volunteerprofile', ['profile_id'], ['id'])
    op.drop_constraint(op.f('volunteerproject_profile_id_fkey'), 'volunteerproject', type_='foreignkey')
    op.create_foreign_key(None, 'volunteerproject', 'volunteerprofile', ['profile_id'], ['id'])
    op.drop_constraint(op.f('volunteerskill_profile_id_fkey'), 'volunteerskill', type_='foreignkey')
    op.create_foreign_key(None, 'volunteerskill', 'volunteerprofile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteerskill', type_='foreignkey')
    op.create_foreign_key(op.f('volunteerskill_profile_id_fkey'), 'volunteerskill', 'volunteerprofile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'volunteerproject', type_='foreignkey')
    op.create_foreign_key(op.f('volunteerproject_profile_id_fkey'), 'volunteerproject', 'volunteerprofile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'volunteerexperience', type_='foreignkey')
    op.create_foreign_key(op.f('volunteerexperience_profile_id_fkey'), 'volunteerexperience', 'volunteerprofile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user', 'push_notifications')
    op.drop_column('user', 'sms_notifications')
    op.drop_column('user', 'email_notifications')
    # ### end Alembic commands ###
